name: NPM Package Install test
on:
  push:
  schedule:
    - cron: "25 * * * *"
jobs:
  test-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: |
          npm install
          npm run test
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
          npm run in
